// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Muek.Engine
{
    internal static unsafe partial class MuekEngine
    {
        const string __DllName = "muek_engine";





        [DllImport(__DllName, EntryPoint = "receive_tracks_proto", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void receive_tracks_proto(TrackProto* ptr, int len);

        [DllImport(__DllName, EntryPoint = "rust_receive_array", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rust_receive_array(MyClassRepr* ptr, int len);

        [DllImport(__DllName, EntryPoint = "my_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int my_add(int x, int y);

        [DllImport(__DllName, EntryPoint = "alloc_u8_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ByteBuffer* alloc_u8_string();

        [DllImport(__DllName, EntryPoint = "get_string_length", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int get_string_length(ByteBuffer* ptr);

        [DllImport(__DllName, EntryPoint = "free_c_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_c_string(byte* str);

        [DllImport(__DllName, EntryPoint = "init_vst_box", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void init_vst_box();

        [DllImport(__DllName, EntryPoint = "run_vst_instance_by_path", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void run_vst_instance_by_path(ushort* utf16_str, int utf16_len);

        [DllImport(__DllName, EntryPoint = "run_vst_instance_by_path_with_handle", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void run_vst_instance_by_path_with_handle(ushort* utf16_str, int utf16_len, nuint hwnd);

        [DllImport(__DllName, EntryPoint = "verify_vst_instance_by_path", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ByteBuffer* verify_vst_instance_by_path(ushort* utf16_str, int utf16_len);

        [DllImport(__DllName, EntryPoint = "cache_clip_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void cache_clip_data(ushort* utf16_str, int utf16_len, float* data_ptr, int len);

        [DllImport(__DllName, EntryPoint = "sync_all_clips", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sync_all_clips(ClipProto* ptr, int len);

        [DllImport(__DllName, EntryPoint = "spawn_audio_thread", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void spawn_audio_thread();

        [DllImport(__DllName, EntryPoint = "get_current_position_beat", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float get_current_position_beat();

        [DllImport(__DllName, EntryPoint = "stream_play", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void stream_play(float beat);

        [DllImport(__DllName, EntryPoint = "stream_stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void stream_stop([MarshalAs(UnmanagedType.U1)] bool stop);

        [DllImport(__DllName, EntryPoint = "set_position_beat", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_position_beat(float beat);

    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct MyClassRepr
    {
        public int id;
        public float* value;
        public int len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TrackProto
    {
        public int track_id;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ClipProto
    {
        public ushort* clip_id;
        public int clip_id_len;
        public float start_time;
        public float end_time;
    }



}
