// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Muek.Engine
{
    internal static unsafe partial class MuekEngine
    {
        const string __DllName = "muek_engine";





        [DllImport(__DllName, EntryPoint = "rust_receive_array", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void rust_receive_array(MyClassRepr* ptr, int len);

        [DllImport(__DllName, EntryPoint = "my_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int my_add(int x, int y);

        [DllImport(__DllName, EntryPoint = "alloc_u8_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ByteBuffer* alloc_u8_string();


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct MyClassRepr
    {
        public int id;
        public float* value;
        public int len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
    }



}
